### ISSUE TITLE
Please bundle Rclone in the AppImage

### ISSUE THREAD

**Issue by probonopd** [dimitrov-adrian/RcloneTray#1]
As per the AppImage philosophy, everything an application needs to run should be bundled right inside the AppImage, so that it can be used without having to download or install additional stuff. So can RcloneTray.AppImage please be bundled to include Rclone?

![](https://github.com/AppImage/appimage.github.io/blob/bb4c335b626f47b1530ed3f489a49d477c3ae597/database/RcloneTray/screenshot.png?raw=true)

Reference:
https://github.com/AppImage/appimage.github.io/pull/936

**Comment by dimitrov-adrian** [comment]
Yes, you are right. I have checked the license and seems it's possible to bundle Rclone within the app.

I will remove the downloader and will include the binary.

Thanks!

**Comment by dimitrov-adrian** [comment]
It's bundled now.
