### ISSUE TITLE
Rclone Mount with B2 Fails

### ISSUE THREAD

**Issue by hudsonsecurity** [dimitrov-adrian/RcloneTray#2]
fails because you need to specify remote:bucket the mount command is missing the :bucketvar value

**Comment by dimitrov-adrian** [comment]
Yeah, with providers that requires buckets mount/sync functions does not works.

May be need to add required field or to disable mount/sync and such bookmarks to be used only as base for aliases.

Thanks for the report, I will think for solution in next update.

**Comment by dimitrov-adrian** [comment]
Have added fields to specify bucket in providers that required it. Thanks.
